[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx prisma generate && npx prisma db push --accept-data-loss && node src/seed.js && node src/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
